services:
  mock:
    image: caddy
    command:
      - caddy
      - run
      - -c
      - /media/Caddyfile
    volumes:
      - ./acceptance-tests/mock:/media
    ports:
      - 8081:8081

  hurl:
    image: ghcr.io/orange-opensource/hurl:latest
    volumes:
      - ./acceptance-tests/test-cases:/tests:ro
    depends_on:
      caddylura:
        condition: service_healthy
    entrypoint:
      - tail
      - -f
      - /dev/null

  caddylura:
    environment:
      BACKEND_HOST: http://mock:8081
    image: golang:1.22
    working_dir: /media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/__ready"]
      start_period: "10s"
    depends_on:
      - mock
    ports:
      - 8082:8082
    command:
      - go
      - run
      - /media/cmd/caddy/
      - run
      - -c
      - /media/Caddyfile
    volumes:
      - ./:/media

